# https://taskfile.dev

version: '3'

tasks:
  start:
    cmds:
      - uv run streamlit run app.py
  format:
    cmds:
      - uv run ruff format
  lfut:fetch:
    cmds:
      - curl -L https://raw.githubusercontent.com/fantinodavide/SquadLayerList/main/layers.json -o layers_upstream.json
      - rm layers.json
      - mv layers_upstream.json layers.json
  lfut:update:
    cmds:
      - uv run LFUT_from_json.py
